# Site settings
title: "Sức Khoẻ của Đoàn Bình"
url-title: "Cuộc Sống Tốt"
description: "Sức Khoẻ"
paginate: 100
url: "https://argustech.info"
permalink: /:year/:month/:title/
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
